---
apiVersion: v1
kind: ConfigMap
metadata:
  name: genesis
  namespace: {{ .Release.Namespace }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: genesis-template
  namespace: {{ .Release.Namespace }}
data:
  genesis.json : |-
      {
          "config": {
              "homesteadBlock": 0,
              "eip150Block": 0,
              "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
              "eip155Block": 0,
              "eip158Block": 0,
              "petersburgBlock": 0,
              "constantinopleBlock": 0,
              "byzantiumBlock": 0,
      {{if eq .Values.concensus "tendermint"}}
              "tendermint": {
                  "policy": 0,
                  "block-period": 1
              },
      {{else if eq .Values.concensus "istanbul"}}
              "istanbul": {
                  "policy": 0,
                  "epoch": 30000,
                  "contract-deployer": "0x0000000000000000000000000000000000000001",
                  "bytecode": "",
              "abi": ""
              },
      {{end}}
            "chainId": {{ .Values.chainid }},
            "autonityContract": {
                "deployer": "0x0000000000000000000000000000000000000002",
                "bytecode": "",
                "abi": "",
                "minGasPrice": 0,
                "governanceOperator": "???",
                "users": []
            }
         },
        "nonce": "0x0",
        "timestamp": "0x0",
        "gasLimit": "0xffffffff",
        "difficulty": "0x1",
        "coinbase": "0x0000000000000000000000000000000000000000",
        "number": "0x0",
        "gasUsed": "0x0",
        "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365"
      }
