dist: bionic
sudo: required
cache:
  directories:
  - "$HOME/bin"
before_install:
- mkdir -p ~/bin
- if [ ! -f ~/bin/kubectl ]; then curl -Ls -o ~/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl
  -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl;
  fi
- chmod +x ~/bin/*
- export PATH="~/bin:$PATH"
- pip install awscli --upgrade --user
- sudo snap install --channel stable --classic helm
- mkdir -p ~/.aws
- printf "[default] \noutput = json \nregion = eu-west-1\n" > ~/.aws/config
jobs:
  include:
  - if: type = pull_request AND fork = false AND head_repo = clearmatics/charts-ose
      AND commit_message !~ /WIP/
    env:
    - CLUSTER=autonity-eks-prod
    - CHART_NAME=${TRAVIS_PULL_REQUEST_BRANCH}
    script:
    - "./ci/test.sh $CLUSTER $CHART_NAME"
  - if: fork = false AND branch = master AND tag =~ /^(\w|-)*[-]\d+[.]\d+[.]\d+$/
    env:
    - CLUSTER=autonity-eks-prod
    - S3_BUCKET_NAME=charts-ose.clearmatics.com
    - CHART_NAME=$(echo ${TRAVIS_TAG} | sed -E s/-[0-9]+\.[0-9]+\.[0-9]+$//g)
    - RELEASE_VERSION=$(echo ${TRAVIS_TAG} | grep -Eo [0-9]+\.[0-9]+\.[0-9]+$)
    script:
    - aws eks update-kubeconfig --name ${CLUSTER}
    - kubectl -n kube-system get pods
    - "./ci/test.sh $CLUSTER $CHART_NAME $RELEASE_VERSION"
    - "./ci/deploy_to_repo.sh $S3_BUCKET_NAME $CHART_NAME $RELEASE_VERSION"
env:
  global:
  - secure: Wf32Bi4WmZjdAaKUEHm7damAWMZQv3+oab6xm737EA0dVzCBFcR4E+erwo25b/a4u0VkHD82nSv/mkx2RRPx8ZKNF9p2Q8S4smA4s4SrBLYwZ9+G5VhsxY5hchHh8DjXNuFa1yWUex5ZejUIsWXn1SheIOhHpnWgWaxDkZEdaVebqkQ55tlR/bbR72G8i7ueGJ3T9squ51latbotKySzUs2y/lbKcabAILWYiSlfrlQnGZxC1nH9u1SxcqNFxKjaAqThZw/PDmA8PbaGwIvapGSfxWGdAUWeuCNnbJADaSawcXNBTqCFBID1wGSmMJHx0s1SKkaJv/9YBn+MMRpJ/pDHpgrn01IVzDlzmHIcZvSd73s/1gVDg63IWUVaI2xctdYQrNODyVGUcE8Pcu8nuAdKoZCu5zmrnC7DOSo84VSCJd5P/agkN/dgysFvquHf2I/VG5j7Pw1lol/aF+dkW+Y/jPEl6lr5Of2a6htV/m/NsxZvrFxLtP0CnY+a6aEUZ6yrrAGeNkVAx8Ybh0r7HyMp5nhDJpgaHwSKD15Jn/08mfYbdNf3v1aK5MjhjYGxiv3pmZld86F/JDIFTDUNnjca7yzgB9fHyvkYhDy8BYDLaQeouSbE+r5DV1tcScvgtjLX1/bqAfLL+PSCnxEilkWqytHHXWMBCARGQ9A7a+Y=
  - secure: enRbJNkYE5WARvkEuPLcrKRmh1WiBh8NK42Zl3i0vtZpKGd+A6aQJm29jngRo9HGSK2+CPmSE5HZOt05oxVpPmQ+1TDA7tRXWeJuMQoBLiCSPCvU576t5x5eBVxBxmuYOJuUmj24+cNqL8GG0NNYvWK5FsQthAU2NDISFi0QfhAgCFNsPDx0mUK7sMKxKRwao5IRRRy4IRrfWCQrzvDJF3b5XY4TGFZC3KoR4nFb1dMNm5tGQEpW2lnqGHENMRPP8/+Yyoc80/kAJlIG85WeM/2IH8+NV4UDoHdpIUFNsZj8U++ysyh+lTNQ0WyvksW/JH1cTd20ZrnoIUMA1D0DrW5lqVIxllHhp79gNca56nyzRca1i+8hlAJuCd2xUe74X0sD/+fPmSFCCQIzfclnbJpHgdYgFEjFo0Je1JZFaku+qmLcjAP1Ky8mDyYHI7Z9EQOxPvnbYXIkGKeyk5mcT6mwAfjre7eE4pKcCOILLbxhknh9bFFDbW+OsiGsocn1MBsqgyOEpEQiZ+P6L04Lxf0VzouFc2amfmo654IpF+q1l6B3JGIPtp7zK1N0GqvHj6CgtqOV/qEmo9v9f69FLuz3ZoGT4jbb3co1PphD0/maOPjJF3U2+6qmLx9ukkB9xdHfOKuu2UtPV9z0VKxBmPHpwQhYKO1KFSuVJ5VTzIU=
notifications:
  slack:
    rooms:
      secure: is+EApQDFHhFcWcsNL4qbLeJCmK6RUTPqgiykAAeI56TQgVOCQMLa/hJRHJin9hmIoT2f45hz683hQnAZUlV+Yb6Pn9mSx3B/BD6OcVEPC2cgpkDm80qCYD2FxnfJRKSBeMB0ErhKi+YAtE587nYENOgkZustVLe8TyDouash9bd1OR4Pn5FnfnneCf2GuuCrq+8V0llkbeI11MeNEdTo66uxGHSYxdieMl0qdn07IUxUcj51xYi1C+mh0Q1xNIQZSbs/3GnKBouS7Je5eJLxCQ1mmz5yMU3WrIhYptpUdcIlldpuo+8qL9+mzU+1MJtqcsUqrKUWqQoTYVYk5zw4KmruqIc6pzkO+Uc6OlRf0/4vL7+xGy4h80InlzcCaImqUVaA/wO13zQ6BemAh1DeL+EOyMVP5cgLcle01n88xuk1CZxLk5e7OwZaoM7QBqILNLPcpyukRmCOzVsJEnTJkbe193/+760odcVwH6AEZEFGrLaoBc8RMxkXan3X0X8fz81NtQ8GFefOjtfeJsT9zhC0TaewZRyNzX1LnkUFQwKsfXZ20PMmHs7cUcL1g5XpgwRjWA4Bg1+5ObQFKPTzgwa21661PwaOQnxEbQMRKsbt5rRDZ2cUe7vlPqP6hUULc69B4Fql0YPRq0ttRKtMkf2nktN7+IrbDd+eqbsu6k=
