---

imageAutonity:
  repository: clearmatics/autonity
  tag: v0.2.1

imageAutonity_init:
  repository: clearmatics/autonity-init
  tag: v1.0.3

image_eth_keys_generator:
  repository: clearmatics/eth-keys-generator
  tag: v0.1.0

image_init_ceremony:
  repository: clearmatics/init-ceremony
  tag: v0.0.2

image_nginx:
  repository: nginx
  tag: 1.17-alpine

testFramework:
  image: "dduportal/bats"
  tag: "0.4.0"

networkid: 444888

rpc_http_basic_auth_enabled: false
rpc_https_enabled: false

rpc:
  tls_crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURYVENDQWtXZ0F3SUJBZ0lKQU5Nc1RDTWpmRlVCTUEwR0NTcUdTSWIzRFFFQkN3VUFNRVV4Q3pBSkJnTlYKQkFZVEFrZENNUTh3RFFZRFZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVVNQklHQTFVRQpDZ3dMUTJ4bFlYSnRZWFJwWTNNd0hoY05NVGt3T1RFM01UUXlOREl5V2hjTk1qQXdPVEUyTVRReU5ESXlXakJGCk1Rc3dDUVlEVlFRR0V3SkhRakVQTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhEQVpNYjI1a2IyNHgKRkRBU0JnTlZCQW9NQzBOc1pXRnliV0YwYVdOek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQgpDZ0tDQVFFQXpXMTY1V1huWFBoZk0zUHJaOFFiY1ArOFJrTFdkeHpYc3pVZk1UdjMyZzg1cHlvdXlYdVNyU2M0CkRzMlJmOXpDeWIvd2V2OXVTRXdxWUFqWjVMT2RSNFk3OEJsem9NTFN2bmlRNVNVN3lLY3lZd0RCUWlmamh1VGoKQjV4ZDBUbmhQd00xS012Vkc2dHRHSnRtejVRUU5pNkg0MjIrSmVXTWVZeDE3bHpjS3pRbW52M1gzSzRycmdRZApQYWgvSlVrNjBrSlpvWkJhUmJ0ck0zOW92Q3d2VlRYeHZkSFV5Y1IvRllsZ21rdi85cmtPdmI4MXRJSDNrUVNmCk8relM5bXVOdTVJc1YveDNPVHRzMUdWMVJUdy9qbHBsVHBSRjNrYisyM3lyNzRVcExoNnpPaEZOU1hLMGRsRGEKeHVBcDl0YzNIb09BWi9zb0UzUjh4TVAzRHpRaDJ3SURBUUFCbzFBd1RqQWRCZ05WSFE0RUZnUVU0ZHFPTG14RwpnMlhMR2czcGx5OVZoYVptQW9Vd0h3WURWUjBqQkJnd0ZvQVU0ZHFPTG14R2cyWExHZzNwbHk5VmhhWm1Bb1V3CkRBWURWUjBUQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBY2p6ek9adG1OVVRGWWZCVDllL3MKZ25GT1V4VGxtelZ4dWFsZXBLVHRIeHdabnFXNkN6anlKWGNmV0lVME1OK2pUc2NsaDFxekNybU9SdVc2WjZqMwpGYmt2RlVZaUxRamZic21nUnZxK1lUaGhScVVRbUtLL3UzejlQcjFiaWRURlF5R29hc0NacGJ5Z0hKeWRXbW90CkVmaEpyNWtoMGJidnA4Y2kvWUMweSt5U1g1QnBQSHRPQW1iUFRqSXhTYnRoMGR0ZHdWclFKL1c5MnlkQ3NWU1YKdkdQRkpjSnBiSWZkNTdIM3FacmE5UnBMK1c0dEliN05DNGtHRjZmVW5HR0tqbVBaUkNoTVI0dDZOYWJIZkZSZApnc2tWeC9saCtGUStDRE96RmkzUjYvY0VlVk9mU3lMejJJT3pPQ2dsVVNxcFhOc1UrUUpod3pPRjl4OUdJZWhsCnVRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls_key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRE5iWHJsWmVkYytGOHoKYyt0bnhCdHcvN3hHUXRaM0hOZXpOUjh4Ty9mYUR6bW5LaTdKZTVLdEp6Z096WkYvM01MSnYvQjYvMjVJVENwZwpDTm5rczUxSGhqdndHWE9nd3RLK2VKRGxKVHZJcHpKakFNRkNKK09HNU9NSG5GM1JPZUUvQXpVb3k5VWJxMjBZCm0yYlBsQkEyTG9mamJiNGw1WXg1akhYdVhOd3JOQ2FlL2RmY3JpdXVCQjA5cUg4bFNUclNRbG1oa0ZwRnUyc3oKZjJpOExDOVZOZkc5MGRUSnhIOFZpV0NhUy8vMnVRNjl2elcwZ2ZlUkJKODc3TkwyYTQyN2tpeFgvSGM1TzJ6VQpaWFZGUEQrT1dtVk9sRVhlUnY3YmZLdnZoU2t1SHJNNkVVMUpjclIyVU5yRzRDbjIxemNlZzRCbit5Z1RkSHpFCncvY1BOQ0hiQWdNQkFBRUNnZ0VBUFlDcWk2V1B1Q2p3TDdKajV5UXlad2xacjl0dzVDWnhlY2pNdHV2U1Q2bkIKUkFnQUMvaUFPSEVHZW9BWE1LWENkNjZNYS9hdmFOdk0wQVcyWHA5YjFqOGRFTXc5N3dLRkg5dHUzZnZnd3pregpmNnFKTWFwSmwyaE5oRWpQV2NXdlp6TXBwallvYm1sTGQxT0hXMXhqNGlUYU1ELzU3dFNqMHZ3M2pvNmtxQllpCnBiTE5Lc1pBODJMMkMyWk9mbXRyMHdGeVZ3bzc4THArRUp2VXhpK252S2ZsaUJWOVpJM1V1amM3aFNiaFRkKzIKdzZlNDNjU3JPSmtTVzFzaFhhajdqUWMwOE1UbGtnZ0NTamQwUDIzY1h2TDNqZXZjRzkxL0dqcm9ZdjFzQXJVagpWRDcrVTREUXJEU0JNUFg0RWZzMW9UMXA2ckhmOXpmTVZKdTA5SnlnVVFLQmdRRHFGRWZuMUhqZzVlQmoxOHdQCmluNDE1T0JCSlBnZkZtWEZHcmlNNDVXL2tmYnRPRU1BZU9vRy9rQmFUVWxxd3AzR1VMQWxnajZWUk5venlSNDcKVVh1eERxZ2ZYSGFmVGVBa29CWGFWQWJjZGhXUklQbEhWdEkrSWUzMUdKMFlwYmZjdWtKOW5EVHZoYmN1ZkZYYwpqQWIxYUtSVndWYTd3bmZXcEZTTGJJakFDUUtCZ1FEZ3FsRjlGMlBCeHdGdU1GbUl5aGNsa04vck5OY2gyUDdMCnhxSDRIb1BwRmIrcE92ckdxdmZCcWV4NzVBQXB3ejluQkZrdGlIK2ZqUVVOa1dWOHhRcXIzWlZwNUdzVVFESDcKdTBNUGoxMm5TNVJMQTQvVFRxUDFTN1pzQnlVSXkwc0I5R0Y3SEcyVnpNVXVMdmdsa2xSNE1KdEs5RnE1UVRkRApWemhhald2RHd3S0JnUURGcE9veDdVMURWOVhuZDhadE9Ocm9WcUNqWUx2QVJBRWFORDJ2ZUZwd3JxWjRGaEU4CnpOdU5uQkJxTHVmV3BRemk3aTVNL1hRcVJVQ1lpVEJsbForREdJVU1OZDVURkVZMXBwWE5DelhmNERURm5ibmQKYW9tS3ZNdFhMN2sxbm5kb2dEeTBJcmp2cFUvT2lGMVhJMFNjNGdZZ0FtZGhrZ250eWtNNGxpUEJRUUtCZ0UxYQp0MFlQMkp3dXpoSkhlWHg4d0syQmpXZXB3T3o1anZsUXdoSHhSOC9vV2g2Rm5UVHNSdlFhY3I5UmlMRFlkaXNkCk55dFRWVVgxUXlraHg4VEcvMTZmbzhOYkQzZGdoeFU2cStOZXBJdG1uWCtha1ZuYk9ON0xtOXJrTnQ4cFNBRTcKU0prZjk2ZGRZd0w4enhuNG9UYmszWU5ZVVNoNkNQSVp4T0NBMHZzTEFvR0FjbDN6czRwcmQyY3lXTmZqVVpxbAp4UDMvME9YdERpM1pwQm0vTkFja2l4bk94aUJFMEtTWEh2Ymhwc1ZBM3FBS3hYbUlMVFNId1VuRjJLd1ZGdlgvCk9kZC81YzMxcWcvUHVIcGVEUkZwdEE5N0FqeHhmY3FJeUxyTVB6QSt6SXVlR1dsTE9sTVp5MnNieDlCUkplMVgKK1gxY0NzekRmUWtXY0t4VzVObDN5cG89Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
  dhparam_pem: LS0tLS1CRUdJTiBESCBQQVJBTUVURVJTLS0tLS0KTUlJQ0NBS0NBZ0VBMDBCeW1HQmlHazBjWDRSTnZrcGtES2tmeFlXUnhlaGhEK2tJYVordEJ6NjZIaHhmTHhtMgpvNkxsYldjZnhqL1hiU1RVdVJaUHNWM1N0eWhnK2VPY1dKS3FUL0drWE1VaG1kbkMxSmlpbEx5ZkxGMzBhOE1pCmV1UjZ5OUczcDJQald1ZFFQUllKZWZWREJwbXZmWmYxaFI3NmVIM0RNU2dGazhpWlNjTG9YRk9WMldDd1JzdVQKdVhGVEZlVlJLTXpVSWsrLzdVOFBReVJJK1NXSkFrY2dpNDk1ak9nNVVpNjAxMEw3bXRLeWdQOTJBd2Y3ekNhbQp6UkVCNlpabXFOUkt3TFcwNXU0bk92Q09VSUN2MlJJaFV3OTRtU2dlU2ZpcXI0TzRLSW1vcHlubUxQN1lzWVRqCnhqR0NuMlR3RnQxaXpaN3g0Z0VKd1Y5ZDZodTlIYWVhdzBIVEppZEJwLzJIZnBBZ3orZVZldmVnYUxNZTBTcm0KS0dITkZMUGFwTldQQkI2KzNGVlllMXVJS29XLzRhTExoT01UM2tlbGhqYTZzYXdRM3hPazYxZDNkZ1BuZnhENwptTnZwRXRjZ1FqVE04V3c5TlFwV1E2bGdwY2NWNDltbU1UajY1MlRidVpuNVhJNkhtajdCemtoMnJCd3pWbVV3CmNPTi9qVlNYUm5NSmU3QUdGSlJKMnBjRjA2T0liM3lvaXo3Rm5nZnArVDI5ZWVGejFjN1creXV5NFcyY2dwNWgKSU9PVlphTTRMVytlbnBDZURtQlk5ZkI2dWNZWnlrVEtpNUF4dUEyR1dFdHNDVXppb2xqMXllT1pLTXVzSUU1VApwRFRpcnB5SGMwakUxUkxmRG1VNnRIOHNEUXJwa1R2ZVhOODRvOUtQcWsxYk1nNXlQWDZVbTdNQ0FRST0KLS0tLS1FTkQgREggUEFSQU1FVEVSUy0tLS0tCg==


# Options for genesis block. Must be the same for all validator nodes (optional value only for new networks)
genesis:
  config:
    homesteadBlock: 0
    eip150Block: 0
    eip150Hash: '0x0000000000000000000000000000000000000000000000000000000000000000'
    eip155Block: 0
    eip158Block: 0
    petersburgBlock: 0
    constantinopleBlock: 0
    byzantiumBlock: 0
    tendermint:
      policy: 0
      block-period: 1
    chainId: 1489
    autonityContract:
      deployer: '0x0000000000000000000000000000000000000002'
      bytecode: ''
      abi: ''
      minGasPrice: 10000000000000
      governanceOperator: '0x4982763697d8e806b24eD52078B29870490Ee126'
      users:
      - enode: fqdn://val-5.autonity.online
        type: validator
        stake: 50000
      - enode: fqdn://val-6.autonity.online
        type: validator
        stake: 50000
      - enode: fqdn://val-7.autonity.online
        type: validator
        stake: 50000
      - enode: fqdn://val-8.autonity.online
        type: validator
        stake: 50000
  nonce: '0x0'
  timestamp: '0x0'
  gasLimit: '0x5F5E100'
  difficulty: '0x1'
  coinbase: '0x0000000000000000000000000000000000000000'
  number: '0x0'
  gasUsed: '0x0'
  parentHash: '0x0000000000000000000000000000000000000000000000000000000000000000'
  mixHash: '0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365'
  alloc:
    '0x71f3998Cb779B612b1B88aF3A078828C87c543DF':
      balance: '0x200000000000000000000000000000000000000000000000000000000000000'
